### PR TITLE
feat(website): AGPL Notice in footer 

### PR DESCRIPTION
**Pull request by sambacha**
## 📝 Summary

AGPL Notice in footer

## ⛱ Motivation and Context

AGPL Notice

## 📚 References

---

## ✅ I have run these commands

* [ ] `make lint`
* [ ] `make test-race`
* [ ] `go mod tidy`
* [ ] I have seen and agree to `CONTRIBUTING.md`

### CODE REVIEW

**Comment by sambacha** [comment]
Please **do not merge this pr** without first resolving https://github.com/flashbots/mev-boost-relay/issues/141 and https://github.com/flashbots/mev-boost-relay/issues/140

**Comment by metachris** [comment]
thanks, but that footer is unnecessary on the homepage. interesting question you've raised in the issues though.

**Comment by sambacha** [comment]
> thanks, but that footer is unnecessary on the homepage. interesting question you've raised in the issues though.

just making our changes available per your license

**Comment by metachris** [comment]
I think you just need to make your repository public, rather than creating PRs here with your changes.

**Comment by sambacha** [comment]
> I think you just need to make your repository public, rather than creating PRs here with your changes.

we have made it open how else would we have opened a PR?

**Comment by metachris** [comment]
For reference: https://github.com/manifoldfinance/mev-boost-relay

**Pull request closed without merging**
