### PR TITLE
support for custom eth networks

### PR DESCRIPTION
**Pull request by metachris**
## 📝 Summary

Allow to specify custom network parameters instead of only the predefined ones. This simplifies participating in custom testnets and mainnet shadow forks.

To do so, use `--network custom` and set the details through these environment variables:

* `GENESIS_FORK_VERSION`
* `GENESIS_VALIDATORS_ROOT`
* `BELLATRIX_FORK_VERSION`
* `CAPELLA_FORK_VERSION`

---

## ✅ I have run these commands

* [x] `make lint`
* [x] `make test-race`
* [x] `go mod tidy`
* [x] I have seen and agree to `CONTRIBUTING.md`

### CODE REVIEW

**Comment by dewindtk** [comment]
Hi. Are these 4 enviromental variables the only ones I must define? I am containerizing the housekeeping servic in Docker while defining these envs in my compose. However, I get an error saying 

level=fatal msg="error getting network details" error="invalid fork version" service=relay/housekeeper version=dev

Thanks in advance for your response.

**Comment by dewindtk** [comment]
For more context, here is the genesis file of the custom Network I have up:
```
CONFIG_NAME: interop
PRESET_BASE: interop

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16

DENEB_FORK_VERSION: 0x20000093

# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 6

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
```

**Comment by metachris** [comment]
@dewindtk perhaps this guide is helpful: https://gist.github.com/metachris/66df812f2920e6b0047afb9fdaf7df91

In general, the relay has been confirmed working for testnets with these settings:

- run the services with `--network=custom`
- set the following environment variables
    - `GENESIS_FORK_VERSION`
    - `GENESIS_VALIDATORS_ROOT`
    - `BELLATRIX_FORK_VERSION`
    - `CAPELLA_FORK_VERSION`

**Comment by metachris** [comment]
the problem is that you have not been using `--network=custom`, the error message should be better: https://github.com/flashbots/mev-boost-relay/blob/main/common/types.go#L96

**Pull request merged**
