### PR TITLE
[WIP] data-api to export active validators with pubkey -- NEEDS DISCUSSION

### PR DESCRIPTION
**Pull request by metachris**
## 📝 Summary

New data API: `/relay/v1/data/active_validators`

Exports a list of all active validators, combined with their latest registered feeRecipient

Deployed on Sepolia: https://boost-relay-sepolia.flashbots.net/relay/v1/data/active_validators

---

## ✅ I have run these commands

* [x] `make lint`
* [x] `make test-race`
* [x] `go mod tidy`
* [x] I have seen and agree to `CONTRIBUTING.md`

### CODE REVIEW

**Comment by metachris** [comment]
Closing, due to privacy concerns. Should find a better way to look up information if needed.

**Comment by aratz-lasa** [comment]
Hey @metachris I'm curious about the decision of closing this. Where can I find the discussion you had about it? 

My understanding is that this information could be obtained in any case, if you obtain all validators from a beacon node, and then query them one by one against `ValidatorRegistration` using their pubkey. So this may be a a good "nicety" to have. Or am I missing something?

**Comment by metachris** [comment]
@aratz-lasa this actually makes a case for removing the `validatorRegistration`, or to not return the feeRecipient (but maybe just a hash).

It's feels like a possible breach of privacy to dump _all_ validators that are actively using a relay with their feeRecipient.

Depending on the particular needs, there should be better ways to solve it (i.e. privacy preserving proofs).

**Comment by metachris** [comment]
> the feeRecipient info per validator is already public on the blockchain itself

only after a block has been proposed though.

**Comment by metachris** [comment]
Please open a discussion about this on the forum with your need, to continue the conversation about such a feature: https://collective.flashbots.net/c/mev-boost/23

**Pull request closed without merging**
