### PR TITLE
registerValidator with fast JSON decoding only

### PR DESCRIPTION
**Pull request by metachris**
## 📝 Summary

Processing validator registrations with [buger/jsonparser](https://github.com/buger/jsonparser) only.

---

## ✅ I have run these commands

* [x] `make lint`
* [x] `make test-race`
* [x] `go mod tidy`
* [x] I have seen and agree to `CONTRIBUTING.md`

### CODE REVIEW

**Comment by metachris** [comment]
been running in Goerli + Sepolia for a while

**Comment by metachris** [comment]
deployed to prod earlier today

**Review by michaelneuder — APPROVED** [review]
LGTM

**Comment by metachris** [comment]
Did a bit more cleanup, and made sure we don't run into a possible int64 overflow with using `time.Unix(...)`

**Pull request merged**
